[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/'
]